### ISSUE TITLE
Missing <repo>/src/sc/src/jq/disp/resolve.jq

### ISSUE THREAD

**Issue by notjames** [annacrombie/sc#1]
Getting `sc` to work so far has failed. The latest (unfixable afaict) error is:

```head: cannot open '/<repo-path>/sc/src/jq/disp/resolve.jq' for reading: No such file or directory```

`resolve.jq` does not exist in the repo or in my local clone or any history as far as I can tell. /shrug

**Comment by annacrombie** [comment]
Sorry, it isn't really finished, but it was working alright for me.  To be honest I didn't expect anyone else to try it out to soon.  I'm working on adding tests at the moment.

For the time being though, can you tell me what command you were running?

**Comment by annacrombie** [comment]
Also, I just pushed up an `env` command that prints out the versions of all the dependencies.  If you could pull down that and run
```
$ sc env
```
tnat would be awesome!

**Comment by notjames** [comment]
yeah, I saw it added to the JSON tooling github repo and thought I'd check it out. So here's some of the info you requested:

```
 $  sc env
find (GNU findutils) 4.6.0.187-5dae
git version 2.19.1
jq-1.5-1-a5b5cbe
mktemp (GNU coreutils) 8.28
tree v1.7.0 (c) 1996 - 2014 by Steve Baker, Thomas Moore, Francesc Rocher, Florian Sesser, Kyosuke Tokoro 
wcache not found
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
sc 0.1.0
```
Now this is a good thing to have. I am not able to find "wcache" as something I can install on my Ubuntu machine (18.10). The closest thing I have to it in apt is ccache, which I installed. That isn't it. I even searched all the repos on my system for `/usr/bin/wcache` -- no dice. I googled it. Nothing. I checked for ppas. Nothing. So some instructions on how to install that would be helpful. The command I'm running is `sc resolve earthlibraries`

**Comment by notjames** [comment]
I symlinked (band-aid) wcache to ccache btw...that's when I get the missing `resolve.jq` error btw. It's doubtful that the missing wcache/ccache would have any bearing on the missing `resolve.jq`.

**Comment by annacrombie** [comment]
Okay, the problem is that `wcache` is another tool I made, and it is doubtful that `ccache` would be a viable replacement.  `wcache` is a `wget` wrapper that basically downloads files to a centralized cache, and upon successive requests for the same url, will give you the cached version, reducing unnecessary requests for relatively static content.  There is a flag in `wcache` that causes it to echo the path to the cached file and it is this path that is used in the call to `jq`.  Therefore, the reason `sc` is looking for a file named `resolve.jq` is because whenever `ccache` gets run, its output is being used as part of a path.

Here is the repo for `wcache`: http://github.com/annacrombie/wcache.

I didn't really explain this requirement at all in the README.md, and I doubt many people would want to install both `sc` and `wcache` separately, so to fix the problem, I bundled `wcache` as a submodule of `sc` and added a wrapper that uses the bundled version (a2f771a).  Since you already cloned this repo, you will have to  manually initialize the new submodules.  Or you can just re-clone:

```
git clone --recurse-submodules https://github.com/annacrombie/sc
```

Hopefully that will fix the problem.

**Comment by notjames** [comment]
OK, cool. That got me further. Looks like there's another dependency problem. Your `column` args don't seem to match what my `column` args are. This could be a version disparity. Are you using Mac or some builtin function? My `column` doesn't have a `-N` argument.:

```
[sc log] [debug] checking /home/<user>/<repo>/sc/data/cache/api.soundcloud.com/resolve/earthlibraries@ (36s old), best-by 86400
[sc log] [debug] its fresh!
column: invalid option -- 'N'
usage: column [-txne] [-c columns] [-s sep] [file ...]
[sc log] [error] jq error in /home/<user>/<repo>/sc/src/jq/disp/user.jq
while parsing /home/<user>/<repo>/sc/data/cache/api.soundcloud.com/users/509984022$
```

You might want to document the fact that an API client id is required to use this tool and that a problem exists where soundcloud is no longer offering API Client IDs (until further notice it seems). There's a way around this but it requires seeking someone else's client ID from github.

**Comment by annacrombie** [comment]
In regard to `column` mine reports `column from util-linux 2.33`, 

```
       -N, --table-columns names
              Specify  the  columns  names  by comma separated list of names. The names are used for the table header or to address column in
              option arguments.
```

I was actually planning on implementing a change that would avoid the need for me to use `-N` at all, so I will go ahead and do that.

**Comment by notjames** [comment]
Cool! So yeah, you're one version ahead of me on `util-linux`

```
$ sudo dpkg -l util-linux
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-=============================================================================================
ii  util-linux                                   2.32-0.1ubuntu2             amd64                       miscellaneous system utilities
```

and for some reason, `columns` doesn't even come in `util-linux` for me so it sounds like you're probably using 19.04?

```
$ sudo apt-file search $(which column)
autogen: /usr/bin/columns
bsdmainutils: /usr/bin/column
```

**Comment by annacrombie** [comment]
As far as an api key is concerned, I thought the same as you did until I read [this](https://github.com/Soundnode/soundnode-app#configuration).  I meant to link to it in the readme, but hadn't yet because I haven't decided the best way to go about it.  I could also ship with a few keys to use as fallbacks.

**Comment by annacrombie** [comment]
I'm actually running Gentoo and my `sys-apps/util-linux-2.33-r1` does come with `column`.  Idk, maybe relying on `column` at all is a bad idea.

**Comment by notjames** [comment]
Yeah, that's a nuanced tool. It's a cool one, but I guarantee there will be problems with it at least in the short term.

**Comment by annacrombie** [comment]
Okay, the latest commit no longer requires `column` to have a `-N` flag :).

**Comment by notjames** [comment]
Yup! That worked!
